require('smart-splits').setup({})
vim.keymap.set('n', '<Left>', require('smart-splits').resize_left)
vim.keymap.set('n', '<Down>', require('smart-splits').resize_down)
vim.keymap.set('n', '<Up>', require('smart-splits').resize_up)
vim.keymap.set('n', '<Right>', require('smart-splits').resize_right)
